image: node:12.13

cache:
  paths:
    - node_modules/

stages:
  - linter
  - test

services:
  - mongo

default:
  before_script:
    - npm install

lint:
  stage: linter
  script:
  - npm run lint

integration:
  stage: test
  script:
  - openssl genrsa -out server.key.pem 2048
  - openssl req -new -sha256 -key server.key.pem -out server.csr.pem
  - openssl x509 -req -in server.csr.pem -signkey server.key.pem -out server.cert.pem
  - cp .env.example .env
  - npm run test
