image: node:12.13

cache:
  paths:
    - node_modules/

stages:
  - linter
  - test

default:
  before_script:
    - npm install

lint:
  stage: linter
  script:
    - npm run lint

integration:
  stage: test
  services:
    - mongo
  
  variables:
    DB_HOST= 'localhost'
    MONGO_HOST= 'mongodb://localhost:27017/blank_api'
    NODE_ENV: 'test'
  script:
    - cp .env.example .env
    - openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=FR/ST=France/L=_/O=_/CN=_" -keyout server.key.pem -out server.cert.pem
    - npm start
    - npm run test
