image: node:12.13

cache:
  paths:
    - node_modules/

stages:
  - linter
  - test

lint:
  before_script:
    - npm install
  stage: linter
  script:
    - npm run lint

integration:
  before_script:
    - npm install
  stage: test
  services:
    - mongo
  
  variables:
    MONGO_HOST: 'mongodb://mongo/blank_api'
   
  script:
    - cp .env.example .env
    - openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=FR/ST=France/L=_/O=_/CN=_" -keyout server.key.pem -out server.cert.pem
    - npm run test
