image: node:12.13

cache:
  paths:
    - node_modules/

stages:
  - linter
  - test

default:
  before_script:
    - npm install

lint:
  stage: linter
  script:
  - npm run lint

integration:
  stage: test
  script:
  - npm run test
