version: "3.1"

services:
  nodeapi:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - .:/var/www/blank_nodejs_api/
    environment:
      MONGO_HOST: mongodb://mongodb:27017/blank_api
      NODE_ENV: development
      RUN_ON_DOCKER:
    command: ./entrypoint.sh
  mongodb:
    image: mongo:5.0.3
    ports:
      - 8081:8081
    volumes:
      - mongodb-data:/data/db
    restart: always
volumes:
  mongodb-data: