name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0 * * ?"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: display local pwd
        run: pwd
      - name: Display local files
        run: ls -la
      - name: Build the docker-compose stack
        run:  docker-compose -f docker.test/docker-compose.yml up --build --abort-on-container-exit
