name: Node Api run tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  schedule:
  - cron: "0 0 * * ?"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run:  docker-compose -f docker.test/docker-compose.yml up --build --abort-on-container-exit
