name: Build image and push it to azure

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 2
          format: 'YYYY-MM-DD-HH-mm-ss'
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build the docker-compose and run integration tests
        run:  docker-compose -f docker.test/docker-compose.yml up --build --abort-on-container-exit
      
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
           docker build --build-arg ARG_JWT_SECRET=${{ secrets.JWT_SECRET }} --build-arg ARG_MONGO_HOST="${{ secrets.MONGO_HOST }}" -f ./docker.production/Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/base_nodejs_api:${{ steps.time.outputs.time }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/base_nodejs_api:latest
           docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/base_nodejs_api:${{ steps.time.outputs.time }}
           docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/base_nodejs_api:latest
           
      - name: 'Deploy to Azure Container Instances image with timestamp'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.DNS_NAME_LABEL }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/base_nodejs_api:${{ steps.time.outputs.time }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: basenodejsapi
          location: 'francecentral'
          
      - name: 'Deploy to Azure Container Instances latest image'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.DNS_NAME_LABEL }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/base_nodejs_api:latest
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: basenodejsapi
          location: 'francecentral'
  
